/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Wallet from './Wallet';

/**
 * The GetAccountResponse model module.
 * @module model/GetAccountResponse
 * @version 0.1.0
 */
class GetAccountResponse {
    /**
     * Constructs a new <code>GetAccountResponse</code>.
     * @alias module:model/GetAccountResponse
     * @param accountNumber {String} 
     * @param balance {Number} 
     * @param accountIsActivate {Boolean} 
     * @param methodOfPayment {module:model/Wallet} 
     * @param loyaltyCredit {Number} 
     */
    constructor(accountNumber, balance, accountIsActivate, methodOfPayment, loyaltyCredit) { 
        
        GetAccountResponse.initialize(this, accountNumber, balance, accountIsActivate, methodOfPayment, loyaltyCredit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountNumber, balance, accountIsActivate, methodOfPayment, loyaltyCredit) { 
        obj['account_number'] = accountNumber;
        obj['balance'] = balance;
        obj['account_is_activate'] = accountIsActivate;
        obj['method_of_payment'] = methodOfPayment;
        obj['loyalty_credit'] = loyaltyCredit;
    }

    /**
     * Constructs a <code>GetAccountResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAccountResponse} obj Optional instance to populate.
     * @return {module:model/GetAccountResponse} The populated <code>GetAccountResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAccountResponse();

            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('account_is_activate')) {
                obj['account_is_activate'] = ApiClient.convertToType(data['account_is_activate'], 'Boolean');
            }
            if (data.hasOwnProperty('method_of_payment')) {
                obj['method_of_payment'] = Wallet.constructFromObject(data['method_of_payment']);
            }
            if (data.hasOwnProperty('loyalty_credit')) {
                obj['loyalty_credit'] = ApiClient.convertToType(data['loyalty_credit'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAccountResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAccountResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetAccountResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['account_number'] && !(typeof data['account_number'] === 'string' || data['account_number'] instanceof String)) {
            throw new Error("Expected the field `account_number` to be a primitive type in the JSON string but got " + data['account_number']);
        }

        return true;
    }


}

GetAccountResponse.RequiredProperties = ["account_number", "balance", "account_is_activate", "method_of_payment", "loyalty_credit"];

/**
 * @member {String} account_number
 */
GetAccountResponse.prototype['account_number'] = undefined;

/**
 * @member {Number} balance
 */
GetAccountResponse.prototype['balance'] = undefined;

/**
 * @member {Boolean} account_is_activate
 */
GetAccountResponse.prototype['account_is_activate'] = undefined;

/**
 * @member {module:model/Wallet} method_of_payment
 */
GetAccountResponse.prototype['method_of_payment'] = undefined;

/**
 * @member {Number} loyalty_credit
 */
GetAccountResponse.prototype['loyalty_credit'] = undefined;






export default GetAccountResponse;

