/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductModel from './ProductModel';
import TransactionStatusEnum from './TransactionStatusEnum';
import Wallet from './Wallet';

/**
 * The GetOneTransaction model module.
 * @module model/GetOneTransaction
 * @version 0.1.0
 */
class GetOneTransaction {
    /**
     * Constructs a new <code>GetOneTransaction</code>.
     * @alias module:model/GetOneTransaction
     * @param orderId {String} 
     * @param methodOfPayment {Array.<module:model/Wallet>} 
     * @param amount {Number} 
     * @param amountToPay {Number} 
     * @param currency {String} 
     * @param createdAt {String} 
     * @param transactionStatus {module:model/TransactionStatusEnum} 
     * @param products {Array.<module:model/ProductModel>} 
     * @param isDone {Boolean} 
     * @param isEscrow {Boolean} 
     * @param isMerchant {Boolean} 
     * @param checkoutUrl {String} 
     */
    constructor(orderId, methodOfPayment, amount, amountToPay, currency, createdAt, transactionStatus, products, isDone, isEscrow, isMerchant, checkoutUrl) { 
        
        GetOneTransaction.initialize(this, orderId, methodOfPayment, amount, amountToPay, currency, createdAt, transactionStatus, products, isDone, isEscrow, isMerchant, checkoutUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId, methodOfPayment, amount, amountToPay, currency, createdAt, transactionStatus, products, isDone, isEscrow, isMerchant, checkoutUrl) { 
        obj['order_id'] = orderId;
        obj['method_of_payment'] = methodOfPayment;
        obj['amount'] = amount;
        obj['amount_to_pay'] = amountToPay;
        obj['currency'] = currency;
        obj['created_at'] = createdAt;
        obj['transaction_status'] = transactionStatus;
        obj['products'] = products;
        obj['is_done'] = isDone;
        obj['is_escrow'] = isEscrow;
        obj['is_merchant'] = isMerchant;
        obj['checkout_url'] = checkoutUrl;
    }

    /**
     * Constructs a <code>GetOneTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetOneTransaction} obj Optional instance to populate.
     * @return {module:model/GetOneTransaction} The populated <code>GetOneTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetOneTransaction();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('method_of_payment')) {
                obj['method_of_payment'] = ApiClient.convertToType(data['method_of_payment'], [Wallet]);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('amount_to_pay')) {
                obj['amount_to_pay'] = ApiClient.convertToType(data['amount_to_pay'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('transaction_status')) {
                obj['transaction_status'] = TransactionStatusEnum.constructFromObject(data['transaction_status']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [ProductModel]);
            }
            if (data.hasOwnProperty('is_done')) {
                obj['is_done'] = ApiClient.convertToType(data['is_done'], 'Boolean');
            }
            if (data.hasOwnProperty('is_escrow')) {
                obj['is_escrow'] = ApiClient.convertToType(data['is_escrow'], 'Boolean');
            }
            if (data.hasOwnProperty('is_merchant')) {
                obj['is_merchant'] = ApiClient.convertToType(data['is_merchant'], 'Boolean');
            }
            if (data.hasOwnProperty('checkout_url')) {
                obj['checkout_url'] = ApiClient.convertToType(data['checkout_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetOneTransaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetOneTransaction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetOneTransaction.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['order_id'] && !(typeof data['order_id'] === 'string' || data['order_id'] instanceof String)) {
            throw new Error("Expected the field `order_id` to be a primitive type in the JSON string but got " + data['order_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['method_of_payment'])) {
            throw new Error("Expected the field `method_of_payment` to be an array in the JSON data but got " + data['method_of_payment']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                ProductModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['checkout_url'] && !(typeof data['checkout_url'] === 'string' || data['checkout_url'] instanceof String)) {
            throw new Error("Expected the field `checkout_url` to be a primitive type in the JSON string but got " + data['checkout_url']);
        }

        return true;
    }


}

GetOneTransaction.RequiredProperties = ["order_id", "method_of_payment", "amount", "amount_to_pay", "currency", "created_at", "transaction_status", "products", "is_done", "is_escrow", "is_merchant", "checkout_url"];

/**
 * @member {String} order_id
 */
GetOneTransaction.prototype['order_id'] = undefined;

/**
 * @member {Array.<module:model/Wallet>} method_of_payment
 */
GetOneTransaction.prototype['method_of_payment'] = undefined;

/**
 * @member {Number} amount
 */
GetOneTransaction.prototype['amount'] = undefined;

/**
 * @member {Number} amount_to_pay
 */
GetOneTransaction.prototype['amount_to_pay'] = undefined;

/**
 * @member {String} currency
 */
GetOneTransaction.prototype['currency'] = undefined;

/**
 * @member {String} created_at
 */
GetOneTransaction.prototype['created_at'] = undefined;

/**
 * @member {module:model/TransactionStatusEnum} transaction_status
 */
GetOneTransaction.prototype['transaction_status'] = undefined;

/**
 * @member {Array.<module:model/ProductModel>} products
 */
GetOneTransaction.prototype['products'] = undefined;

/**
 * @member {Boolean} is_done
 */
GetOneTransaction.prototype['is_done'] = undefined;

/**
 * @member {Boolean} is_escrow
 */
GetOneTransaction.prototype['is_escrow'] = undefined;

/**
 * @member {Boolean} is_merchant
 */
GetOneTransaction.prototype['is_merchant'] = undefined;

/**
 * @member {String} checkout_url
 */
GetOneTransaction.prototype['checkout_url'] = undefined;






export default GetOneTransaction;

