/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductModel model module.
 * @module model/ProductModel
 * @version 0.1.0
 */
class ProductModel {
    /**
     * Constructs a new <code>ProductModel</code>.
     * @alias module:model/ProductModel
     * @param name {String} 
     * @param category {String} 
     * @param amount {Number} 
     * @param quantity {Number} 
     * @param description {String} 
     */
    constructor(name, category, amount, quantity, description) { 
        
        ProductModel.initialize(this, name, category, amount, quantity, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, category, amount, quantity, description) { 
        obj['name'] = name;
        obj['category'] = category;
        obj['amount'] = amount;
        obj['quantity'] = quantity;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>ProductModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductModel} obj Optional instance to populate.
     * @return {module:model/ProductModel} The populated <code>ProductModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ProductModel.RequiredProperties = ["name", "category", "amount", "quantity", "description"];

/**
 * @member {String} name
 */
ProductModel.prototype['name'] = undefined;

/**
 * @member {String} category
 */
ProductModel.prototype['category'] = undefined;

/**
 * @member {Number} amount
 */
ProductModel.prototype['amount'] = undefined;

/**
 * @member {Number} quantity
 */
ProductModel.prototype['quantity'] = undefined;

/**
 * @member {String} description
 */
ProductModel.prototype['description'] = undefined;






export default ProductModel;

