/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Wallet.
* @enum {}
* @readonly
*/
export default class Wallet {
    
        /**
         * value: "WAVE"
         * @const
         */
        "WAVE" = "WAVE";

    
        /**
         * value: "ORANGE_MONEY"
         * @const
         */
        "ORANGE_MONEY" = "ORANGE_MONEY";

    
        /**
         * value: "FREE_MONEY"
         * @const
         */
        "FREE_MONEY" = "FREE_MONEY";

    

    /**
    * Returns a <code>Wallet</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Wallet} The enum <code>Wallet</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

