/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NabooApiV1);
  }
}(this, function(expect, NabooApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NabooApiV1.GetAccountResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetAccountResponse', function() {
    it('should create an instance of GetAccountResponse', function() {
      // uncomment below and update the code to test GetAccountResponse
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be.a(NabooApiV1.GetAccountResponse);
    });

    it('should have the property accountNumber (base name: "account_number")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property accountIsActivate (base name: "account_is_activate")', function() {
      // uncomment below and update the code to test the property accountIsActivate
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property methodOfPayment (base name: "method_of_payment")', function() {
      // uncomment below and update the code to test the property methodOfPayment
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property loyaltyCredit (base name: "loyalty_credit")', function() {
      // uncomment below and update the code to test the property loyaltyCredit
      //var instance = new NabooApiV1.GetAccountResponse();
      //expect(instance).to.be();
    });

  });

}));
