/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NabooApiV1);
  }
}(this, function(expect, NabooApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NabooApiV1.TransactionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionRequest', function() {
    it('should create an instance of TransactionRequest', function() {
      // uncomment below and update the code to test TransactionRequest
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be.a(NabooApiV1.TransactionRequest);
    });

    it('should have the property methodOfPayment (base name: "method_of_payment")', function() {
      // uncomment below and update the code to test the property methodOfPayment
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

    it('should have the property products (base name: "products")', function() {
      // uncomment below and update the code to test the property products
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

    it('should have the property successUrl (base name: "success_url")', function() {
      // uncomment below and update the code to test the property successUrl
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

    it('should have the property errorUrl (base name: "error_url")', function() {
      // uncomment below and update the code to test the property errorUrl
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

    it('should have the property isEscrow (base name: "is_escrow")', function() {
      // uncomment below and update the code to test the property isEscrow
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

    it('should have the property isMerchant (base name: "is_merchant")', function() {
      // uncomment below and update the code to test the property isMerchant
      //var instance = new NabooApiV1.TransactionRequest();
      //expect(instance).to.be();
    });

  });

}));
